export enum SocketEvent {
  Init = "1",
  Move = "2",
  Attack = "3",
  AttackOther = "4",
  Rotate = "5",
  RotateOther = "6",
  UseItem = "7",
  UseItemOther = "8",
  Craft = "9",
  StatsUpdate = "10",
  InventoryUpdate = "11",
  HelmetUpdate = "12",
  HelmetUpdateOther = "13",
  WeaponOrToolUpdate = "14",
  WeaponOrToolUpdateOther = "15",
  AnimateCollectable = "16",
  MovementUpdate = "17",
  MovementUpdateOther = "18",
  AttackStart = "19",
  AttackStop = "20",
  PlayerInitialization = "21",
  PlayerRemove = "22",
}
