export enum SocketEvent {
  Init = "0",
  Move = "1",
  Attack = "2",
  Rotate = "3",
  UseItem = "4",
  Craft = "5",
  StatsUpdate = "6",
  InventoryUpdate = "7",
  HelmetUpdate = "8",
  WeaponOrToolUpdate = "9",
  AnimateCollectable = "10",
  MovementUpdate = "11",
  AttackStart = "12",
  AttackStop = "13",
}
